application: big-natao
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2                                                                  
  version: latest 

handlers:
- url: /static/imgs
  static_dir: static/imgs
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: main.app
